import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getDocument } from "pdfjs-dist/legacy/build/pdf.mjs";
import { sylabiCatalog } from "../src/data/sylabiCatalog.ts";
import { itemsToLines } from "../src/lib/pdf/extractPdfLines.ts";
import { parsePdfLines } from "../src/lib/pdf/parsePdfDocument.ts";
import type { PdfTextItem } from "../src/lib/pdf/types.ts";
import type { SyllabusOutlineData } from "../src/types/syllabus.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const outFile = join(root, "src/data/sylabiCatalogCache.ts");

function fontSizeFromTransform(transform: number[]): number {
  return Math.hypot(transform[0], transform[1]);
}

async function loadPdfLines(relativePath: string) {
  const data = new Uint8Array(
    readFileSync(join(publicDir, relativePath.replace(/^\//, ""))),
  );
  const pdf = await getDocument({ data }).promise;
  const allLines = [];

  for (let pageNum = 1; pageNum <= pdf.numPages; pageNum++) {
    const page = await pdf.getPage(pageNum);
    const content = await page.getTextContent();
    const items: PdfTextItem[] = content.items
      .filter((item): item is typeof item & { str: string } => "str" in item)
      .map((item) => ({
        text: item.str,
        x: item.transform[4],
        y: item.transform[5],
        width: item.width,
        height: item.height,
        fontSize: fontSizeFromTransform(item.transform),
      }));
    allLines.push(...itemsToLines(pageNum, items));
  }

  return allLines;
}

const cache: Record<string, SyllabusOutlineData> = {};
const errors: Record<string, string> = {};

for (const entry of sylabiCatalog) {
  const relativePath = entry.pdfPath.replace(/^\//, "");
  process.stdout.write(`Parsing ${relativePath}… `);

  try {
    const lines = await loadPdfLines(entry.pdfPath);
    cache[entry.id] = parsePdfLines(lines, {
      fileName: entry.fileName,
      catalogSubject: entry.subject,
      catalogTitle: entry.title,
    });
    process.stdout.write("ok\n");
  } catch (error) {
    const message = error instanceof Error ? error.message : "Parse failed";
    errors[entry.id] = message;
    process.stdout.write(`failed (${message})\n`);
  }
}

const fileContents = `/** Auto-generated by npm run cache:sylabi-outlines — do not edit manually. */
import type { SyllabusOutlineData } from "../types/syllabus";

export const sylabiCatalogCache: Record<string, SyllabusOutlineData> = ${JSON.stringify(cache, null, 2)};

export const sylabiCatalogParseErrors: Record<string, string> = ${JSON.stringify(errors, null, 2)};
`;

writeFileSync(outFile, fileContents);
console.log(
  `Wrote ${Object.keys(cache).length} parsed outlines (${Object.keys(errors).length} failures) to ${outFile}`,
);
