/** Auto-generated by npm run catalog:sylabi — do not edit manually. */
export interface SylabiCatalogEntry {
  id: string;
  subject: string;
  title: string;
  fileName: string;
  pdfPath: string;
}

export const sylabiCatalogSubjects: string[] = [
  "Abnormal Psychology",
  "Algorithms",
  "Anatomy and Physiology 1",
  "Anatomy and Physiology 2",
  "Biochemistry",
  "Business Communications",
  "Business Law",
  "Business Statistics",
  "Data Structures",
  "Differential Equations",
  "Engineering Dynamics",
  "Genetics",
  "Introduction to Programming",
  "Managerial Accounting",
  "Marketing",
  "Microeconomics",
  "Operating Systems",
  "Thermodynamics",
  "_unclassified"
];

export const sylabiCatalog: SylabiCatalogEntry[] = [
  {
    "id": "unclassified-arabic-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Arabic Sec 2024 25",
    "fileName": "Arabic_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Arabic_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-assamese-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Assamese Sec 2024 25",
    "fileName": "Assamese_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Assamese_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-bahasa-melayu-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Bahasa Melayu Sec 2024 25",
    "fileName": "Bahasa_Melayu_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Bahasa_Melayu_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-bengali-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Bengali Sec 2024 25",
    "fileName": "Bengali_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Bengali_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-bhoti-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Bhoti Sec 2024 25",
    "fileName": "Bhoti_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Bhoti_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-bhutia-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Bhutia Sec 2024 25",
    "fileName": "Bhutia_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Bhutia_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-bodo-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Bodo Sec 2024 25",
    "fileName": "Bodo_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Bodo_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-carnatic-percussion-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Carnatic Percussion Sec 2024 25",
    "fileName": "Carnatic_Percussion_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Carnatic_Percussion_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-carnatic-vocal-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Carnatic Vocal Sec 2024 25",
    "fileName": "Carnatic_Vocal_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Carnatic_Vocal_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-fall-2025-syllabus-part-ii-pdf",
    "subject": "_unclassified",
    "title": "fall 2025 syllabus part ii",
    "fileName": "fall_2025_syllabus_part_ii.pdf",
    "pdfPath": "/sylabi/_unclassified/fall_2025_syllabus_part_ii.pdf"
  },
  {
    "id": "unclassified-french-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "French Sec 2024 25",
    "fileName": "French_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/French_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-german-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "German Sec 2024 25",
    "fileName": "German_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/German_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-gujarati-sec-2024-25-pdf",
    "subject": "_unclassified",
    "title": "Gujarati Sec 2024 25",
    "fileName": "Gujarati_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/_unclassified/Gujarati_Sec_2024-25.pdf"
  },
  {
    "id": "unclassified-preparing-course-syllabus-unknown-pdf",
    "subject": "_unclassified",
    "title": "preparing course syllabus unknown",
    "fileName": "preparing_course_syllabus_unknown.pdf",
    "pdfPath": "/sylabi/_unclassified/preparing_course_syllabus_unknown.pdf"
  },
  {
    "id": "unclassified-sl-syllabus-template-pdf",
    "subject": "_unclassified",
    "title": "sl syllabus template",
    "fileName": "sl-syllabus-template.pdf",
    "pdfPath": "/sylabi/_unclassified/sl-syllabus-template.pdf"
  },
  {
    "id": "unclassified-syllabus-spring-2025-pdf",
    "subject": "_unclassified",
    "title": "Syllabus Spring 2025",
    "fileName": "Syllabus-Spring-2025.pdf",
    "pdfPath": "/sylabi/_unclassified/Syllabus-Spring-2025.pdf"
  },
  {
    "id": "unclassified-tips-creating-learning-centered-syllabus-8252020-pdf",
    "subject": "_unclassified",
    "title": "tips creating learning centered syllabus 8252020",
    "fileName": "tips-creating-learning-centered-syllabus-8252020.pdf",
    "pdfPath": "/sylabi/_unclassified/tips-creating-learning-centered-syllabus-8252020.pdf"
  },
  {
    "id": "abnormal-psychology-2024s-psych-38-e7414-hedlund-pdf",
    "subject": "Abnormal Psychology",
    "title": "2024S PSYCH 38 E7414 Hedlund",
    "fileName": "2024S-PSYCH-38-E7414-Hedlund.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/2024S-PSYCH-38-E7414-Hedlund.pdf"
  },
  {
    "id": "abnormal-psychology-clp2140syllabus-pdf",
    "subject": "Abnormal Psychology",
    "title": "CLP2140Syllabus",
    "fileName": "CLP2140Syllabus.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/CLP2140Syllabus.pdf"
  },
  {
    "id": "abnormal-psychology-clp3144-summerbsyllabusupdated-pdf",
    "subject": "Abnormal Psychology",
    "title": "CLP3144 Summer BSyllabus Updated",
    "fileName": "CLP3144_SummerBSyllabusUpdated.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/CLP3144_SummerBSyllabusUpdated.pdf"
  },
  {
    "id": "abnormal-psychology-harris-psyc-2320-151-sp25-pdf",
    "subject": "Abnormal Psychology",
    "title": "HARRIS PSYC 2320 151 SP25",
    "fileName": "HARRIS_PSYC_2320_151_SP25.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/HARRIS_PSYC_2320_151_SP25.pdf"
  },
  {
    "id": "abnormal-psychology-psy-214-2-syllabus-pdf",
    "subject": "Abnormal Psychology",
    "title": "Psy 214 2 Syllabus",
    "fileName": "Psy-214-2-Syllabus.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/Psy-214-2-Syllabus.pdf"
  },
  {
    "id": "abnormal-psychology-psy-480-syllabus-pdf",
    "subject": "Abnormal Psychology",
    "title": "psy 480 syllabus",
    "fileName": "psy-480-syllabus.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/psy-480-syllabus.pdf"
  },
  {
    "id": "abnormal-psychology-psyc-3082-2-0-s1-syllabus-pdf",
    "subject": "Abnormal Psychology",
    "title": "PSYC 3082 2.0 s1 Syllabus",
    "fileName": "PSYC_3082_2.0_s1_Syllabus.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/PSYC_3082_2.0_s1_Syllabus.pdf"
  },
  {
    "id": "abnormal-psychology-syl-london-psych-ua9035l01-loewenthal-pdf",
    "subject": "Abnormal Psychology",
    "title": "Syl London PSYCH UA9035L01 Loewenthal",
    "fileName": "Syl_London_PSYCH-UA9035L01_Loewenthal.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/Syl_London_PSYCH-UA9035L01_Loewenthal.pdf"
  },
  {
    "id": "abnormal-psychology-syllabus-pdf",
    "subject": "Abnormal Psychology",
    "title": "syllabus",
    "fileName": "syllabus.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/syllabus.pdf"
  },
  {
    "id": "abnormal-psychology-visual-syllabus-abnormal-f22-website-pdf",
    "subject": "Abnormal Psychology",
    "title": "Visual Syllabus Abnormal F22 Website",
    "fileName": "Visual_Syllabus_Abnormal_F22_Website.pdf",
    "pdfPath": "/sylabi/Abnormal Psychology/Visual_Syllabus_Abnormal_F22_Website.pdf"
  },
  {
    "id": "algorithms-mit-cs-301-pdf",
    "subject": "Algorithms",
    "title": "MIT CS 301",
    "fileName": "MIT_CS_-301.pdf",
    "pdfPath": "/sylabi/Algorithms/MIT_CS_-301.pdf"
  },
  {
    "id": "algorithms-syllabus-pdf",
    "subject": "Algorithms",
    "title": "syllabus",
    "fileName": "syllabus.pdf",
    "pdfPath": "/sylabi/Algorithms/syllabus.pdf"
  },
  {
    "id": "algorithms-syllabus-algorithms-pdf",
    "subject": "Algorithms",
    "title": "Syllabus Algorithms",
    "fileName": "Syllabus_Algorithms.pdf",
    "pdfPath": "/sylabi/Algorithms/Syllabus_Algorithms.pdf"
  },
  {
    "id": "algorithms-syllabus-cpe593-pdf",
    "subject": "Algorithms",
    "title": "syllabus cpe593",
    "fileName": "syllabus_cpe593.pdf",
    "pdfPath": "/sylabi/Algorithms/syllabus_cpe593.pdf"
  },
  {
    "id": "algorithms-the-politics-of-algorithms-syllabus-pdf",
    "subject": "Algorithms",
    "title": "The Politics of Algorithms Syllabus",
    "fileName": "The-Politics-of-Algorithms_Syllabus.pdf",
    "pdfPath": "/sylabi/Algorithms/The-Politics-of-Algorithms_Syllabus.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-80747-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "80747",
    "fileName": "80747.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/80747.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-anatphys1a-syllabus-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "ANATPHYS1A Syllabus",
    "fileName": "ANATPHYS1A-Syllabus.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/ANATPHYS1A-Syllabus.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-bio201-anatomy-physiology-i-v6-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "BIO201 Anatomy Physiology I V6",
    "fileName": "BIO201_Anatomy_Physiology_I_V6.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/BIO201_Anatomy_Physiology_I_V6.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-biol-0055-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "biol 0055",
    "fileName": "biol-0055.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/biol-0055.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-biol181-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "BIOL181",
    "fileName": "BIOL181.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/BIOL181.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-nur210-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "NUR210",
    "fileName": "NUR210.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/NUR210.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-nurs-211-syllabus-fall-2017-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "NURS 211 Syllabus Fall 2017",
    "fileName": "NURS-211-Syllabus-Fall-2017.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/NURS-211-Syllabus-Fall-2017.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-nus210-healthcare-foundations-syllabus-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "NUS210 Healthcare Foundations Syllabus",
    "fileName": "NUS210_-_Healthcare_Foundations_Syllabus.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/NUS210_-_Healthcare_Foundations_Syllabus.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-va-anatomy-and-physiology-1-syllabus-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "VA Anatomy and Physiology 1 Syllabus",
    "fileName": "VA-Anatomy-and-Physiology-1-Syllabus.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/VA-Anatomy-and-Physiology-1-Syllabus.pdf"
  },
  {
    "id": "anatomy-and-physiology-1-warnerpacific-nurs-210-syllabus-pdf",
    "subject": "Anatomy and Physiology 1",
    "title": "Warner Pacific NURS 210 Syllabus",
    "fileName": "WarnerPacific_NURS-210-Syllabus.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 1/WarnerPacific_NURS-210-Syllabus.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs201-20100226-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS201 20100226",
    "fileName": "NURS201-20100226.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS201-20100226.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs202-20190301-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS202 20190301",
    "fileName": "NURS202-20190301.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS202-20190301.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs204-20110128-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS204 20110128",
    "fileName": "NURS204-20110128.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS204-20110128.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs301-20100226-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS301 20100226",
    "fileName": "NURS301-20100226.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS301-20100226.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs303-20051125-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS303 20051125",
    "fileName": "NURS303-20051125.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS303-20051125.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs304-20031126-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS304 20031126",
    "fileName": "NURS304-20031126.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS304-20031126.pdf"
  },
  {
    "id": "anatomy-and-physiology-2-nurs406-20180126-pdf",
    "subject": "Anatomy and Physiology 2",
    "title": "NURS406 20180126",
    "fileName": "NURS406-20180126.pdf",
    "pdfPath": "/sylabi/Anatomy and Physiology 2/NURS406-20180126.pdf"
  },
  {
    "id": "biochemistry-biochem-501-syllabus-fall2023-pdf",
    "subject": "Biochemistry",
    "title": "BIOCHEM 501 Syllabus Fall2023",
    "fileName": "BIOCHEM_501_Syllabus_Fall2023.pdf",
    "pdfPath": "/sylabi/Biochemistry/BIOCHEM_501_Syllabus_Fall2023.pdf"
  },
  {
    "id": "biochemistry-biochem-507-syllabus-fall2022-pdf",
    "subject": "Biochemistry",
    "title": "BIOCHEM 507 Syllabus Fall2022",
    "fileName": "BIOCHEM_507_Syllabus_Fall2022.pdf",
    "pdfPath": "/sylabi/Biochemistry/BIOCHEM_507_Syllabus_Fall2022.pdf"
  },
  {
    "id": "biochemistry-biochemistry-syllabus-paper-distribution-08022024153505-pdf",
    "subject": "Biochemistry",
    "title": "biochemistry syllabus Paper distribution 08022024153505",
    "fileName": "biochemistry_syllabus_Paper_distribution_08022024153505.PDF",
    "pdfPath": "/sylabi/Biochemistry/biochemistry_syllabus_Paper_distribution_08022024153505.PDF"
  },
  {
    "id": "biochemistry-chem301-f2021-syllabus-pdf",
    "subject": "Biochemistry",
    "title": "CHEM301 F2021 Syllabus",
    "fileName": "CHEM301_F2021_Syllabus.pdf",
    "pdfPath": "/sylabi/Biochemistry/CHEM301_F2021_Syllabus.pdf"
  },
  {
    "id": "biochemistry-chem301syllabus-f21-pdf",
    "subject": "Biochemistry",
    "title": "CHEM301Syllabus F21",
    "fileName": "CHEM301Syllabus_F21_.pdf",
    "pdfPath": "/sylabi/Biochemistry/CHEM301Syllabus_F21_.pdf"
  },
  {
    "id": "biochemistry-fa21generalbiochemistryisyllabus-pdf",
    "subject": "Biochemistry",
    "title": "Fa21General Biochemistry ISyllabus",
    "fileName": "Fa21GeneralBiochemistryISyllabus.pdf",
    "pdfPath": "/sylabi/Biochemistry/Fa21GeneralBiochemistryISyllabus.pdf"
  },
  {
    "id": "biochemistry-generalbiochemistry-syllabus-spring2024-pdf",
    "subject": "Biochemistry",
    "title": "General Biochemistry Syllabus Spring2024",
    "fileName": "GeneralBiochemistry_Syllabus_Spring2024.pdf",
    "pdfPath": "/sylabi/Biochemistry/GeneralBiochemistry_Syllabus_Spring2024.pdf"
  },
  {
    "id": "biochemistry-m-sc-medical-biochemistry-syllabus-examination-2019-pdf",
    "subject": "Biochemistry",
    "title": "M.Sc . Medical Biochemistry Syllabus Examination 2019",
    "fileName": "M.Sc_.-Medical-Biochemistry-Syllabus-Examination-2019.pdf",
    "pdfPath": "/sylabi/Biochemistry/M.Sc_.-Medical-Biochemistry-Syllabus-Examination-2019.pdf"
  },
  {
    "id": "business-communications-2023s-bus-52-v5166-wilshusen-pdf",
    "subject": "Business Communications",
    "title": "2023S BUS 52 V5166 Wilshusen",
    "fileName": "2023S-BUS-52-V5166-Wilshusen.pdf",
    "pdfPath": "/sylabi/Business Communications/2023S-BUS-52-V5166-Wilshusen.pdf"
  },
  {
    "id": "business-communications-2024s-bus-52-v7638-wilshusen-pdf",
    "subject": "Business Communications",
    "title": "2024S BUS 52 V7638 Wilshusen",
    "fileName": "2024S-BUS-52-V7638-Wilshusen.pdf",
    "pdfPath": "/sylabi/Business Communications/2024S-BUS-52-V7638-Wilshusen.pdf"
  },
  {
    "id": "business-communications-80331-pdf",
    "subject": "Business Communications",
    "title": "80331",
    "fileName": "80331.pdf",
    "pdfPath": "/sylabi/Business Communications/80331.pdf"
  },
  {
    "id": "business-communications-bcom-430-530-positive-business-communications-syllabus-pdf",
    "subject": "Business Communications",
    "title": "BCOM 430 530 Positive Business Communications Syllabus",
    "fileName": "BCOM-430-530-Positive-Business-Communications-Syllabus.pdf",
    "pdfPath": "/sylabi/Business Communications/BCOM-430-530-Positive-Business-Communications-Syllabus.pdf"
  },
  {
    "id": "business-communications-bus105-business-communication-v6-pdf",
    "subject": "Business Communications",
    "title": "BUS105 Business Communication V6",
    "fileName": "BUS105_Business_Communication_V6.pdf",
    "pdfPath": "/sylabi/Business Communications/BUS105_Business_Communication_V6.pdf"
  },
  {
    "id": "business-communications-bus210-pdf",
    "subject": "Business Communications",
    "title": "BUS210",
    "fileName": "BUS210.pdf",
    "pdfPath": "/sylabi/Business Communications/BUS210.pdf"
  },
  {
    "id": "business-communications-bus210-d3903104-pdf",
    "subject": "Business Communications",
    "title": "bus210 d3903104",
    "fileName": "bus210_d3903104.pdf",
    "pdfPath": "/sylabi/Business Communications/bus210_d3903104.pdf"
  },
  {
    "id": "business-communications-bus210-syllabus-f05-pdf",
    "subject": "Business Communications",
    "title": "bus210 syllabus f05",
    "fileName": "bus210_syllabus_f05.pdf",
    "pdfPath": "/sylabi/Business Communications/bus210_syllabus_f05.pdf"
  },
  {
    "id": "business-communications-bus401-pdf",
    "subject": "Business Communications",
    "title": "BUS401",
    "fileName": "BUS401.pdf",
    "pdfPath": "/sylabi/Business Communications/BUS401.pdf"
  },
  {
    "id": "business-communications-cob-commonsyllabusfall-2025bcom-3304-pdf",
    "subject": "Business Communications",
    "title": "COB Common Syllabus Fall 2025BCOM 3304",
    "fileName": "COB_CommonSyllabusFall-2025BCOM-3304.pdf",
    "pdfPath": "/sylabi/Business Communications/COB_CommonSyllabusFall-2025BCOM-3304.pdf"
  },
  {
    "id": "business-law-bus-110-03-griffin-pdf",
    "subject": "Business Law",
    "title": "bus 110 03 griffin",
    "fileName": "bus-110-03-griffin.pdf",
    "pdfPath": "/sylabi/Business Law/bus-110-03-griffin.pdf"
  },
  {
    "id": "business-law-bus-310-01-ryan-murphy-pdf",
    "subject": "Business Law",
    "title": "bus 310 01 ryan murphy",
    "fileName": "bus-310-01-ryan-murphy.pdf",
    "pdfPath": "/sylabi/Business Law/bus-310-01-ryan-murphy.pdf"
  },
  {
    "id": "business-law-bus-310-03-ryan-murphy-pdf",
    "subject": "Business Law",
    "title": "bus 310 03 ryan murphy",
    "fileName": "bus-310-03-ryan-murphy.pdf",
    "pdfPath": "/sylabi/Business Law/bus-310-03-ryan-murphy.pdf"
  },
  {
    "id": "business-law-busi2301-2a1-spring-2025-pdf",
    "subject": "Business Law",
    "title": "busi2301 2a1 spring 2025",
    "fileName": "busi2301_2a1_spring_2025.pdf",
    "pdfPath": "/sylabi/Business Law/busi2301_2a1_spring_2025.pdf"
  },
  {
    "id": "business-law-business-law-syllabus-pdf",
    "subject": "Business Law",
    "title": "Business Law Syllabus",
    "fileName": "Business_Law_Syllabus.pdf",
    "pdfPath": "/sylabi/Business Law/Business_Law_Syllabus.pdf"
  },
  {
    "id": "business-law-spring-2024-isb-business-law-syllabus-pdf",
    "subject": "Business Law",
    "title": "Spring 2024 ISB Business Law Syllabus",
    "fileName": "Spring_2024_ISB_Business_Law_Syllabus.pdf",
    "pdfPath": "/sylabi/Business Law/Spring_2024_ISB_Business_Law_Syllabus.pdf"
  },
  {
    "id": "business-law-syllabusbus310-2015-pdf",
    "subject": "Business Law",
    "title": "syllabus BUS310 2015",
    "fileName": "syllabusBUS310_2015.pdf",
    "pdfPath": "/sylabi/Business Law/syllabusBUS310_2015.pdf"
  },
  {
    "id": "business-law-syllabus-business-law-pdf",
    "subject": "Business Law",
    "title": "Syllabus Business Law",
    "fileName": "Syllabus_Business_Law.pdf",
    "pdfPath": "/sylabi/Business Law/Syllabus_Business_Law.pdf"
  },
  {
    "id": "business-statistics-bcom-abst-hons-new-pdf",
    "subject": "Business Statistics",
    "title": "BCom ABST Hons new",
    "fileName": "BCom_ABST_Hons_new.pdf",
    "pdfPath": "/sylabi/Business Statistics/BCom_ABST_Hons_new.pdf"
  },
  {
    "id": "business-statistics-coursesyllabus-gradingpolicy-pdf",
    "subject": "Business Statistics",
    "title": "Course Syllabus Grading Policy",
    "fileName": "CourseSyllabus_GradingPolicy.pdf",
    "pdfPath": "/sylabi/Business Statistics/CourseSyllabus_GradingPolicy.pdf"
  },
  {
    "id": "business-statistics-mat150-business-statistics-v4-pdf",
    "subject": "Business Statistics",
    "title": "MAT150 Business Statistics V4",
    "fileName": "MAT150_Business_Statistics_V4.pdf",
    "pdfPath": "/sylabi/Business Statistics/MAT150_Business_Statistics_V4.pdf"
  },
  {
    "id": "business-statistics-sem223-pdf",
    "subject": "Business Statistics",
    "title": "sem223",
    "fileName": "sem223.pdf",
    "pdfPath": "/sylabi/Business Statistics/sem223.pdf"
  },
  {
    "id": "business-statistics-simplesyllabus-spring-2026-osc-2030-019-business-statistics-pdf",
    "subject": "Business Statistics",
    "title": "Simple Syllabus Spring 2026 OSC 2030 019 Business Statistics",
    "fileName": "SimpleSyllabus_Spring-2026-OSC-2030-019-Business-Statistics.pdf",
    "pdfPath": "/sylabi/Business Statistics/SimpleSyllabus_Spring-2026-OSC-2030-019-Business-Statistics.pdf"
  },
  {
    "id": "business-statistics-statssyllabus-pdf",
    "subject": "Business Statistics",
    "title": "statssyllabus",
    "fileName": "statssyllabus.pdf",
    "pdfPath": "/sylabi/Business Statistics/statssyllabus.pdf"
  },
  {
    "id": "business-statistics-syllabus-stat-101-2016-summer-pdf",
    "subject": "Business Statistics",
    "title": "Syllabus STAT 101 2016 Summer",
    "fileName": "Syllabus-STAT-101-2016-Summer.pdf",
    "pdfPath": "/sylabi/Business Statistics/Syllabus-STAT-101-2016-Summer.pdf"
  },
  {
    "id": "business-statistics-syllabus-stat1030-fall2025-pdf",
    "subject": "Business Statistics",
    "title": "syllabus STAT1030 Fall2025",
    "fileName": "syllabus-STAT1030-Fall2025.pdf",
    "pdfPath": "/sylabi/Business Statistics/syllabus-STAT1030-Fall2025.pdf"
  },
  {
    "id": "business-statistics-ug-statistics-syllabus-pdf",
    "subject": "Business Statistics",
    "title": "UG Statistics Syllabus",
    "fileName": "UG_Statistics_Syllabus.pdf",
    "pdfPath": "/sylabi/Business Statistics/UG_Statistics_Syllabus.pdf"
  },
  {
    "id": "business-statistics-vodl7dpnhz6gl0hsbxs26jdbecbfxovqninmpz1v-pdf",
    "subject": "Business Statistics",
    "title": "VOdl7dpn HZ6gl0hsb Xs26Jdb Ecbfx Ovq NInmpz1V",
    "fileName": "VOdl7dpnHZ6gl0hsbXs26JdbEcbfxOvqNInmpz1V.pdf",
    "pdfPath": "/sylabi/Business Statistics/VOdl7dpnHZ6gl0hsbXs26JdbEcbfxOvqNInmpz1V.pdf"
  },
  {
    "id": "data-structures-algorithms-and-data-structures-course-syllabus-codepro-pdf",
    "subject": "Data Structures",
    "title": "Algorithms and Data Structures Course Syllabus Code Pro",
    "fileName": "Algorithms-and-Data-Structures-Course-Syllabus-CodePro.pdf",
    "pdfPath": "/sylabi/Data Structures/Algorithms-and-Data-Structures-Course-Syllabus-CodePro.pdf"
  },
  {
    "id": "data-structures-eecs340-454-s19-syllabus-pdf",
    "subject": "Data Structures",
    "title": "eecs340 454 s19 syllabus",
    "fileName": "eecs340_454_s19_syllabus.pdf",
    "pdfPath": "/sylabi/Data Structures/eecs340_454_s19_syllabus.pdf"
  },
  {
    "id": "data-structures-syllabus-pdf",
    "subject": "Data Structures",
    "title": "Syllabus",
    "fileName": "Syllabus.pdf",
    "pdfPath": "/sylabi/Data Structures/Syllabus.pdf"
  },
  {
    "id": "data-structures-syllabus-algorithms-pdf",
    "subject": "Data Structures",
    "title": "Syllabus Algorithms",
    "fileName": "Syllabus_Algorithms.pdf",
    "pdfPath": "/sylabi/Data Structures/Syllabus_Algorithms.pdf"
  },
  {
    "id": "data-structures-syllabus-b766264b-pdf",
    "subject": "Data Structures",
    "title": "syllabus b766264b",
    "fileName": "syllabus_b766264b.pdf",
    "pdfPath": "/sylabi/Data Structures/syllabus_b766264b.pdf"
  },
  {
    "id": "differential-equations-ap-calculus-bc-sample-syllabus-1-pdf",
    "subject": "Differential Equations",
    "title": "ap calculus bc sample syllabus 1",
    "fileName": "ap-calculus-bc-sample-syllabus-1.pdf",
    "pdfPath": "/sylabi/Differential Equations/ap-calculus-bc-sample-syllabus-1.pdf"
  },
  {
    "id": "engineering-dynamics-eng-329-syllabus-spring-2022-pdf",
    "subject": "Engineering Dynamics",
    "title": "ENG 329 syllabus spring 2022",
    "fileName": "ENG-329-syllabus_spring-2022.pdf",
    "pdfPath": "/sylabi/Engineering Dynamics/ENG-329-syllabus_spring-2022.pdf"
  },
  {
    "id": "genetics-bsc2010-syllabus-spring-2025-1-pdf",
    "subject": "Genetics",
    "title": "BSC2010 syllabus Spring 2025 1",
    "fileName": "BSC2010-syllabus-Spring-2025-1.pdf",
    "pdfPath": "/sylabi/Genetics/BSC2010-syllabus-Spring-2025-1.pdf"
  },
  {
    "id": "introduction-to-programming-carnatic-melodic-sec-2024-25-pdf",
    "subject": "Introduction to Programming",
    "title": "Carnatic Melodic Sec 2024 25",
    "fileName": "Carnatic_Melodic_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/Introduction to Programming/Carnatic_Melodic_Sec_2024-25.pdf"
  },
  {
    "id": "managerial-accounting-elements-of-bk-acc-sec-2024-25-pdf",
    "subject": "Managerial Accounting",
    "title": "Elements of BK Acc Sec 2024 25",
    "fileName": "Elements_of_BK_Acc_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/Managerial Accounting/Elements_of_BK_Acc_Sec_2024-25.pdf"
  },
  {
    "id": "marketing-elements-of-business-sec-2024-25-pdf",
    "subject": "Marketing",
    "title": "Elements of Business Sec 2024 25",
    "fileName": "Elements_of_Business_Sec_2024-25.pdf",
    "pdfPath": "/sylabi/Marketing/Elements_of_Business_Sec_2024-25.pdf"
  },
  {
    "id": "microeconomics-ap-microeconomics-sample-syllabus-1-pdf",
    "subject": "Microeconomics",
    "title": "ap microeconomics sample syllabus 1",
    "fileName": "ap-microeconomics-sample-syllabus-1.pdf",
    "pdfPath": "/sylabi/Microeconomics/ap-microeconomics-sample-syllabus-1.pdf"
  },
  {
    "id": "microeconomics-course-syllabus-microeconomics-v5-1-pdf",
    "subject": "Microeconomics",
    "title": "Course Syllabus Microeconomics V5 1",
    "fileName": "Course_Syllabus_-_Microeconomics_V5__1_.pdf",
    "pdfPath": "/sylabi/Microeconomics/Course_Syllabus_-_Microeconomics_V5__1_.pdf"
  },
  {
    "id": "microeconomics-microeconomics-syllabus-cowen-tabarrok-pdf",
    "subject": "Microeconomics",
    "title": "microeconomics syllabus cowen tabarrok",
    "fileName": "microeconomics-syllabus-cowen-tabarrok.pdf",
    "pdfPath": "/sylabi/Microeconomics/microeconomics-syllabus-cowen-tabarrok.pdf"
  },
  {
    "id": "operating-systems-art226-pdf",
    "subject": "Operating Systems",
    "title": "ART226",
    "fileName": "ART226.pdf",
    "pdfPath": "/sylabi/Operating Systems/ART226.pdf"
  },
  {
    "id": "operating-systems-syllabus-350-jeremy-foltz-pdf",
    "subject": "Operating Systems",
    "title": "Syllabus 350 Jeremy Foltz",
    "fileName": "Syllabus_350_Jeremy_Foltz.pdf",
    "pdfPath": "/sylabi/Operating Systems/Syllabus_350_Jeremy_Foltz.pdf"
  },
  {
    "id": "thermodynamics-asen3113-thermodynamicsandheattransfer-syllabus-spring2023-1172023-finalupdated-pdf",
    "subject": "Thermodynamics",
    "title": "asen3113 thermodynamicsandheattransfer syllabus spring2023 1172023 finalupdated",
    "fileName": "asen3113_thermodynamicsandheattransfer_syllabus_spring2023_1172023_finalupdated.pdf",
    "pdfPath": "/sylabi/Thermodynamics/asen3113_thermodynamicsandheattransfer_syllabus_spring2023_1172023_finalupdated.pdf"
  },
  {
    "id": "thermodynamics-egn3343eng-thermodynamics-pdf",
    "subject": "Thermodynamics",
    "title": "egn3343eng thermodynamics",
    "fileName": "egn3343eng-thermodynamics.pdf",
    "pdfPath": "/sylabi/Thermodynamics/egn3343eng-thermodynamics.pdf"
  },
  {
    "id": "thermodynamics-egn3343thermodynamics-pdf",
    "subject": "Thermodynamics",
    "title": "egn3343thermodynamics",
    "fileName": "egn3343thermodynamics.pdf",
    "pdfPath": "/sylabi/Thermodynamics/egn3343thermodynamics.pdf"
  }
];
